### ISSUE TITLE
ERC20 substreams

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/substreams-antelope#28]
- [ ] add `graph_out` sink `EntityChanges`
https://github.com/streamingfast/substreams-entity-change
- [ ] add `prom_out` sink `PrometheusOperations
https://github.com/pinax-network/substreams-sink-prometheus.rs
- [ ] support all ERC20 smart contract **events** https://ethereum.org/en/developers/docs/standards/tokens/erc-20/
  - [ ] Transfer (`map_transfers`)
  - [ ] Approve (`map_approves`)
- [ ] Support `params` to filter by particular smart contract or all contracts (ex: https://github.com/pinax-network/substreams/tree/develop/eosio.token)

## References
- https://github.com/messari/substreams/tree/master/erc20-holdings
- https://github.com/pinax-network/substreams/tree/develop/eosio.token

**Comment by kr-meet** [comment]
@DenisCarriere hey..i want to work on this. Can you explain what exactly the issue is?

**Comment by DenisCarriere** [comment]
Implemented here => https://github.com/pinax-network/substreams-erc20
