### ISSUE TITLE
Create a substream for AtomicAssets NFTs on EOS and WAX

### ISSUE THREAD

**Issue by chillsauce** [EOS-Nation/substreams-antelope#30]

**Comment by Pelotfr** [comment]
Seem to be blocked by abi2rs decoding problems (in this case decoding Vec<Uint64>) as discussed with Yaro

**Comment by YaroShkvorets** [comment]
Not really blocked. You should be able to use that [modified abi.rs](https://github.com/pinax-network/eos_nfts/blob/develop/src/abi.rs) to track transfer actions.
I've added a `panic` when `transfer` fails to decode, so we should see if it doesn't work for some reason.

Opened an issue: https://github.com/pinax-network/antelope-abi2rs/issues/12
