### ISSUE TITLE
[Substream Proposal] List of Tokens

### ISSUE THREAD

**Issue by fschoell** [EOS-Nation/substreams-antelope#4]
### Goal

Retrieve a list of tokens that are available on the chain. 

### Models

Briefly describe the models that are used as input / output for this Substream

### Maps

Briefly list the maps including their input / output for this Substream

### Stores

Briefly list the stores used in this Substream

### Consumers

Briefly explain how to consume this substream and whether this is a custom consumer or a default sink

**Comment by DenisCarriere** [comment]
Implemented via https://github.com/EOS-Nation/substreams-antelope/tree/develop/substreams/eosio.token

StreamingFast team needs to implement **kV Sink** to make it useful
