### ISSUE TITLE
[Substream Proposal] Token balance for accounts

### ISSUE THREAD

**Issue by fschoell** [EOS-Nation/substreams-antelope#5]
### Goal

Retrieve a list of token balances per account and a list of accounts that hold balances of a certain token. 

### Models

Briefly describe the models that are used as input / output for this Substream

### Maps

Briefly list the maps including their input / output for this Substream

### Stores

Briefly list the stores used in this Substream

### Consumers

Briefly explain how to consume this substream and whether this is a custom consumer or a default sink

**Comment by DenisCarriere** [comment]
Implemented via:

- https://github.com/EOS-Nation/substreams-antelope/tree/develop/substreams/eosio.token

"""
Alex Bourget, [Jan 2, 2023 at 3:25:56 PM]:
I think it would be best to use the kV sink (that is being written), where your key would be something like: owner:contract:SYM -> value, and you could simply override values as you go.. and the kV sink would be queriable by key

And you could easily prefix scan "owner:" to get all the latest token balances
"""
