### ISSUE TITLE
[Substream Proposal] List of token transfers for accounts

### ISSUE THREAD

**Issue by fschoell** [EOS-Nation/substreams-antelope#6]
### Goal

Retrieve a list of incoming / outgoing token transfers for a certain account in a certain period.

### Models

Briefly describe the models that are used as input / output for this Substream

### Maps

Briefly list the maps including their input / output for this Substream

### Stores

Briefly list the stores used in this Substream

### Consumers

Briefly explain how to consume this substream and whether this is a custom consumer or a default sink

**Comment by DenisCarriere** [comment]
Implemented by https://github.com/EOS-Nation/substreams-antelope/tree/develop/substreams/eosio.token
